Masters3/Masters3/Controllers/AdminController.cs
using Masters3.Data;
using Masters3.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Masters3.Controllers
{
    public class AdminController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<User> user;
        private readonly SignInManager<User> signInManager;
        private readonly ApplicationDbContext context;

        public AdminController(ILogger<HomeController> logger, UserManager<User> user, ApplicationDbContext context, SignInManager<User> signInManager)
        {
            _logger = logger;
            this.user = user;
            this.context = context;
            this.signInManager = signInManager;
        }
        public IActionResult statistic()
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;

            var User = context.Users.ToList();
            var category = context.categories.ToList();
            var product = context.products.ToList();
            var order = context.orders.ToList();
            var testimonial = context.testimonials.ToList();

            var tuple = new Tuple<IEnumerable<User>, IEnumerable<Category>, IEnumerable<Product>, IEnumerable<Order>, IEnumerable<Testimonial>>(User, category, product, order, testimonial);
            return View(tuple);
        }
        public async Task<IActionResult> LogOut()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public IActionResult Profile()
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;

            return View(u);
        }
        [HttpPost]
        public async Task<IActionResult> Profile(string Fname, string password, string email, string phone, IFormFile image)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (u != null)
            {
                if (Fname != null && u.UserName != Fname)
                {
                    u.UserName = Fname;
                }
                if (email != null && u.Email != email)
                {
                    u.Email = email;
                }
                if (phone != null && u.PhoneNumber != phone)
                {
                    u.PhoneNumber = phone;
                }
                var fileName = "";
                if (image != null)
                {
                    fileName = Path.GetFileName(image.FileName);
                    u.Imagepath = image.FileName;
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Img", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(fileStream);
                    }
                }
                if (u.UserName == Fname || u.Email == email || u.PhoneNumber == phone || u.Imagepath == fileName)
                {
                    await user.UpdateAsync(u);
                    await context.SaveChangesAsync();
                }
            }

            return View(u);
        }
        [HttpGet]
        public IActionResult User()
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            return View(context.Users.ToList());  
        }
        [HttpPost]
        public IActionResult User(string name)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (name != null)
            return View(context.Users.Where(obj=>obj.UserName== name).ToList()); 
            else
                return View(context.Users.ToList());
        }

        [HttpGet]
        public IActionResult Testimonial()
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;

            return View(context.testimonials.Include(obj=>obj.User).ToList());
        }

        [HttpPost]
        public IActionResult Testimonial(string status,int id)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;

            var tes = context.testimonials.Where(obj => obj.Id == id).FirstOrDefault();
            tes.Status = status;

            context.Update(tes);
            context.SaveChanges();

            return View(context.testimonials.Include(obj => obj.User).ToList());
        }
    }
}

Masters3/Masters3/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Masters3.Data;
using Masters3.Models;

namespace Masters3.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            var applicationDbContext = _context.products.Include(p => p.Categorys);
            return View(await applicationDbContext.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(string name)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (name != null)
                return View(_context.products.Where(obj => obj.Name == name).Include(p => p.Categorys).ToList());
            else
                return View(_context.products.Include(p => p.Categorys).ToList());
        }
        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products
                .Include(p => p.Categorys)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            ViewData["CategoryId"] = new SelectList(_context.categories, "Id", "CategoryName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Quantity,Price,ImagePath,CategoryId")] Product product, IFormFile image  )
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (!ModelState.IsValid)
            {
                var fileName = Path.GetFileName(image.FileName);
                product.ImagePath = image.FileName;
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Img", fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await image.CopyToAsync(fileStream);
                }
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.categories, "Id", "Id", product.CategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.categories, "Id", "CategoryName", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Quantity,Price,ImagePath,CategoryId")] Product product , IFormFile image)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (id != product.Id)
            {
                return NotFound();
            }

            Product c = _context.products.Find(id);
            c.Name = product.Name;
            c.Price = product.Price;
            c.Description = product.Description;
            c.Quantity = product.Quantity;
            //c.ImagePath = product.ImagePath;

            if (image != null)
            {
                var fileName = Path.GetFileName(image.FileName);
                c.ImagePath = image.FileName;
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Img", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await image.CopyToAsync(fileStream);
                }
            }
            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(c);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.categories, "Id", "Id", product.CategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products
                .Include(p => p.Categorys)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var auserID = HttpContext.Session.GetString("IdUser");

            var u = _context.Users.Where(obj => obj.Id == auserID).FirstOrDefault();
            ViewBag.username = u.UserName;
            ViewBag.image = u.Imagepath;
            if (_context.products == null)
            {
                return Problem("Entity set 'ApplicationDbContext.products'  is null.");
            }
            var product = await _context.products.FindAsync(id);
            if (product != null)
            {
                _context.products.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.products?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Masters3/Masters3/Views/Shared/AdminLayout.cshtml
@*<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>*@
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="~/AdminDash/img/icons/icon-48x48.png" />

	<link rel="canonical" href="https://demo-basic.adminkit.io/" />

	<title>AdminKit Demo - Bootstrap 5 Admin Template</title>

	<link href="~/AdminDash/css/app.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
</head>

<body>
	<div class="wrapper">
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
				<a class="sidebar-brand" asp-action="index" asp-controller="Home">
					<span class="align-middle">Admin</span>
				</a>

				<ul class="sidebar-nav">
					<li class="sidebar-header">
						Pages
					</li>

					<li class="sidebar-item active">
						<a class="sidebar-link" asp-action="statistic" asp-controller="Admin">
							<i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Dashboard</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" asp-action="Profile" asp-controller="Admin">
							<i class="align-middle" data-feather="user"></i> <span class="align-middle">Profile</span>
						</a>
					</li>

				

					<li class="sidebar-header">
						Manage Pages
					</li>

					
					<li class="sidebar-item">
						<a class="sidebar-link" asp-action="User" asp-controller="Admin">
							<i class="fas fa-users"></i><span class="align-middle">Users</span>
						</a>
					</li>
				

					<li class="sidebar-item">
						<a class="sidebar-link" asp-action="Index" asp-controller="Categories">
							<i class="align-middle" data-feather="list"></i> <span class="align-middle">Categories</span>
						</a>
					</li>

				

					<li class="sidebar-item">
						<a class="sidebar-link" asp-action="Index" asp-controller="Products">
							<i class="align-middle" data-feather="box"></i> <span class="align-middle">Products</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a class="sidebar-link" asp-action="Testimonial" asp-controller="Admin">
							<i class="align-middle" data-feather="message-circle"></i> <span class="align-middle">Testamonial</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a class="sidebar-link" href="ui-buttons.html">
							<i class="fas fa-shopping-cart"></i> <span class="align-middle">Orders</span>
						</a>
					</li>
					
					<li class="sidebar-item">
						<a class="sidebar-link" asp-action="Create" asp-controller="Stores">
							<i class="far fa-comment"></i> <span class="align-middle">Reviews</span>
						</a>
					</li>
				
				</ul>

			@*	<div class="sidebar-cta">
					<div class="sidebar-cta-content">
						<strong class="d-inline-block mb-2">Upgrade to Pro</strong>
						<div class="mb-3 text-sm">
							Are you looking for more components? Check out our premium version.
						</div>
						<div class="d-grid">
							<a href="upgrade-to-pro.html" class="btn btn-primary">Upgrade to Pro</a>
						</div>
					</div>
				</div>*@
			</div>
		</nav>
		<div class="main">
			<nav class="navbar navbar-expand navbar-light navbar-bg">
				<a class="sidebar-toggle js-sidebar-toggle">
					<i class="hamburger align-self-center"></i>
				</a>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav navbar-align">
					
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
								<i class="align-middle" data-feather="settings"></i>
							</a>

							<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
								<img src="~/img/@ViewBag.image" class="avatar img-fluid rounded me-1" alt="Charles Hall" /> <span class="text-dark">@ViewBag.username</span>
							</a>
							<div class="dropdown-menu dropdown-menu-end">
								<a class="dropdown-item" asp-action="Profile" asp-controller="Admin"><i class="align-middle me-1" data-feather="user"></i> Profile</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" asp-action="LogOut" asp-controller="Admin">Log out</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>

		<main class="content" >
			<div class="container-fluid p-0">
		<div >
			@RenderBody()
		</div>
   
		@*<footer class="footer">
				<div class="container-fluid">
					<div class="row text-muted">
						<div class="col-6 text-start">
							<p class="mb-0">
								<a class="text-muted" href="https://adminkit.io/" target="_blank"><strong>AdminKit</strong></a> &copy;
							</p>
						</div>
						<div class="col-6 text-end">
							<ul class="list-inline">
								<li class="list-inline-item">
									<a class="text-muted" href="https://adminkit.io/" target="_blank">Support</a>
								</li>
								<li class="list-inline-item">
									<a class="text-muted" href="https://adminkit.io/" target="_blank">Help Center</a>
								</li>
								<li class="list-inline-item">
									<a class="text-muted" href="https://adminkit.io/" target="_blank">Privacy</a>
								</li>
								<li class="list-inline-item">
									<a class="text-muted" href="https://adminkit.io/" target="_blank">Terms</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</footer>*@
			</div>
			</main>
	</div>

	<script src="~/AdminDash/js/app.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Masters3/Masters3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Masters3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Masters3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Masters3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Masters3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>